#LEVEL 2 TASK 1 RESTAURANT RATINGS
#ANALYZE THE DISTRIBUTION OF AGG RATINGS AND DETERMINE THE MOST COMMON RATING RANGE

USE TASKS;
SELECT 
  `AGGREGATE RATING`, 
  COUNT(*) AS rating_count
FROM 
  cognifyz
GROUP BY 
  `AGGREGATE RATING`
ORDER BY 
  rating_count DESC;

  
#CAL THE AVG NO OF VOTES REC BY RESTAURANTS

SELECT 
  AVG(Votes) AS average_votes
FROM 
  cognifyz;

